---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ion-sfu.fullname" . }}
  labels:
    {{- include "ion-sfu.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "ion-sfu.fullname" . }}
  replicas: {{ .Values.replicaCount  }}
  selector:
    matchLabels:
      {{- include "ion-sfu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ion-sfu.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp-7000
              containerPort: 7000
              protocol: TCP

            {{- range untilStep (.Values.ports.min|int) (.Values.ports.max|int) 1 }}
            - name: "{{ . }}-udp"
              containerPort: {{ . }}
              protocol: UDP
           {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
            - name: {{ include "ion-sfu.fullname" . }}-volume
              mountPath: /configs/

      volumes:
        - name: {{ include "ion-sfu.fullname" . }}-volume
          configMap:
            name: {{ include "ion-sfu.fullname" . }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
